// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnionWebApi.Models.Contexts;

namespace OnionWebApi.Models.Migrations
{
    [DbContext(typeof(BaseContext))]
    [Migration("20211103205207_addMetodMount")]
    partial class addMetodMount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnionWebApi.Models.Entities.Loans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CreditorId")
                        .HasColumnType("int");

                    b.Property<int>("DebtorId")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentMount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditorId");

                    b.HasIndex("DebtorId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("OnionWebApi.Models.Entities.Pay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<double>("Mount")
                        .HasColumnType("float");

                    b.Property<DateTime>("RealizationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Rstablished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Voucher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pay");
                });

            modelBuilder.Entity("OnionWebApi.Models.Entities.PayL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoansId")
                        .HasColumnType("int");

                    b.Property<int>("PayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoansId");

                    b.HasIndex("PayId");

                    b.ToTable("PayL");
                });

            modelBuilder.Entity("OnionWebApi.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("OnionWebApi.Models.Entities.Loans", b =>
                {
                    b.HasOne("OnionWebApi.Models.Entities.User", "Creditor")
                        .WithMany("CreditorLoans")
                        .HasForeignKey("CreditorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnionWebApi.Models.Entities.User", "Debtor")
                        .WithMany("DebtorLoans")
                        .HasForeignKey("DebtorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creditor");

                    b.Navigation("Debtor");
                });

            modelBuilder.Entity("OnionWebApi.Models.Entities.PayL", b =>
                {
                    b.HasOne("OnionWebApi.Models.Entities.Loans", null)
                        .WithMany("PayLoansEntity")
                        .HasForeignKey("LoansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnionWebApi.Models.Entities.Pay", null)
                        .WithMany("PayLoansEntity")
                        .HasForeignKey("PayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnionWebApi.Models.Entities.Loans", b =>
                {
                    b.Navigation("PayLoansEntity");
                });

            modelBuilder.Entity("OnionWebApi.Models.Entities.Pay", b =>
                {
                    b.Navigation("PayLoansEntity");
                });

            modelBuilder.Entity("OnionWebApi.Models.Entities.User", b =>
                {
                    b.Navigation("CreditorLoans");

                    b.Navigation("DebtorLoans");
                });
#pragma warning restore 612, 618
        }
    }
}
